name: CI

on:
    pull_request:
        branches: [ "main" ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Copiar código do repositório
              uses: actions/checkout@v4
            
            - name: Configurar o uv
              uses: astral-sh/setup-uv@v5
              with:
                enable-cache: true
                version: latest
            
            - name: Sincronizar dependências
              run: uv sync
            
            - name: Instalar navegador Playwright
              run: uv run playwright install chromium --with-deps
            
            - name: Rodar os testes
              run: uv run pytest -v
            
            

