name: WorkFlow Workana

on:
    schedule:
        - cron: '10 13 * * *'
    workflow_dispatch: 

jobs:
    cronjob:
        runs-on: ubuntu-latest
        
        env:
            GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
            SERVER_WEBSHARE: ${{ secrets.SERVER_WEBSHARE }}
            USERNAME_WEBSHARE: ${{ secrets.USERNAME_WEBSHARE }}
            PASSWORD_WEBSHARE: ${{ secrets.PASSWORD_WEBSHARE }}
            # Variáveis de ambiente de e-mail
            SENHA_EMAIL: ${{ secrets.SENHA_EMAIL }}
            HOST: ${{ secrets.HOST }}
            FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
            SMTP_EMAIL: ${{ secrets.SMTP_EMAIL }}
            TO_EMAIL: ${{ secrets.TO_EMAIL }}
            
            PYTHONUNBUFFERED: "1"

        steps:
            - name: Clonar o repositório
              uses: actions/checkout@v4
        
            - name: Instalar o uv e o Pythono
              uses: astral-sh/setup-uv@v5
              with:
                version: 'latest'
                enable-cache: true
            
            - name: Instalar dependências
              run: |
                uv sync
            
            - name: Instalar Navegadores do Playwright
              run: uv run playwright install chromium --with-deps
            
            - name: Rodar o script
              run: uv run main.py